Repository snowplow/documentation, pull requests merged in 2022-12, with the labels that each got.

#204 Move to more nested structure, remove tabs where possible
  docs/collecting-data/collecting-from-own-applications/flutter-tracker/sessions-and-data-model/index.md
  docs/collecting-data/collecting-from-own-applications/flutter-tracker/tracking-events/index.md
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/browser-tracker/browser-tracker-v3-reference/tracker-setup/initialization-options/index.md
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/javascript-tracker-v3/tracker-setup/initialization-options/index.md
  docs/collecting-data/collecting-from-own-applications/react-native-tracker/previous-version/react-native-tracker-v0-reference/index.md
  docs/managing-data-quality/testing-and-qa-workflows/set-up-automated-testing-with-snowplow-micro/example-of-automated-tests/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-advanced-usage/dbt-advanced-operation/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-advanced-usage/dbt-incremental-logic/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-advanced-usage/dbt-user-mapping/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-custom-models/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-media-player-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-mobile-data-model/images/Screenshot-2022-03-25-at-10.50.33.png
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-mobile-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/images/image-3.png
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-operation/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-operation/operation-media-package/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-quickstart/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-tests/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/index.md
  static/_redirects
Labels: cla:yes

#206 Add consent tracking model
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
Labels: cla:yes

#208 Refresh link tracking whenever new link appear in the app
  snowplow.js
  src/helpers/useRefreshTrackinOnMenuToggle.js
  src/theme/DocPage/Layout/Sidebar/index.js
  src/theme/DocSidebar/Desktop/Content/index.js
  src/theme/DocSidebar/Desktop/Content/styles.module.css
  src/theme/Navbar/MobileSidebar/index.js
  src/theme/SearchBar/index.js
  src/theme/SearchBar/styles.css
Labels: cla:no

#218 Add Databricks to BDP Cloud
  docs/feature-comparison/index.md
Labels: cla:no

#219 Bump enrich version to 3.6.1
  README.md
  package.json
  src/componentVersions.js
  yarn.lock
Labels: cla:yes

#220 Update _redirects
  static/_redirects
Labels: cla:yes

#222 Add Snowplow Mini 0.15.1 docs
  docs/pipeline-components-and-applications/snowplow-mini/setup-guide-for-aws/index.md
  docs/pipeline-components-and-applications/snowplow-mini/setup-guide-for-gcp/index.md
  src/componentVersions.js
Labels: cla:yes

#225 Add accelerator redirects
  static/_redirects
Labels: cla:no

#209 Add docs for dbt Fractribution model
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-fractribution-data-model/images/attribution_models_dark.png
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-fractribution-data-model/images/attribution_models_light.png
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-fractribution-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-quickstart/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/index.md
Labels: documentation, cla:yes

#228 Add new config for dbt web package
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/index.md
Labels: do not merge

#230 Update Rust tracker docs for 0.2.0
  docs/collecting-data/collecting-from-own-applications/rust-tracker/adding-data/index.md
  docs/collecting-data/collecting-from-own-applications/rust-tracker/getting-started/index.md
  docs/collecting-data/collecting-from-own-applications/rust-tracker/index.md
  docs/collecting-data/collecting-from-own-applications/rust-tracker/initialization-and-configuration/index.md
  docs/collecting-data/collecting-from-own-applications/rust-tracker/tracking-events/index.md
  src/componentVersions.js
Labels: cla:yes

#235 Update feature comparison with latest inclusions
  docs/feature-comparison/index.md
Labels: cla:no

#227 update dbt normalize docs for version 0.2
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-normalize-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/index.md
Labels: do not merge
