Repository snowplow/documentation, pull requests merged in 2023-01, with the labels that each got.

#238 RDB Loader 5.3.0
  src/componentVersions.js
Labels: cla:yes

#268 Update introduction.md
  docs/introduction.md
Labels: cla:no

#120 Add Snowbridge docs
  docs/contributing/copyright-license/index.md
  docs/destinations/forwarding-events/elasticsearch/index.md
  docs/destinations/forwarding-events/google-tag-manager-server-side/building-an-enriched-event-relay-for-gtm-ss/index.md
  docs/destinations/forwarding-events/google-tag-manager-server-side/index.md
  docs/destinations/forwarding-events/images/forwardingevents-1.png
  docs/destinations/forwarding-events/index.md
  docs/destinations/forwarding-events/native-integrations/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/application-overview/images/snowbridge-architecture.jpg
  docs/destinations/forwarding-events/snowbridge/concepts/application-overview/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/batching-model/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/failure-model/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/sources/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/targets/index.md
  docs/destinations/forwarding-events/snowbridge/concepts/transformations/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/monitoring/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/sources/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/sources/kinesis.md
  docs/destinations/forwarding-events/snowbridge/configuration/sources/pubsub.md
  docs/destinations/forwarding-events/snowbridge/configuration/sources/sqs.md
  docs/destinations/forwarding-events/snowbridge/configuration/sources/stdin.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/eventhub.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/http.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/kafka.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/kinesis.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/pubsub.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/sqs.md
  docs/destinations/forwarding-events/snowbridge/configuration/targets/stdout.md
  docs/destinations/forwarding-events/snowbridge/configuration/telemetry/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/create-a-script/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/examples/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/examples/non-snowplow.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/examples/snowplow.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/javascript-configuration/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/custom-scripts/lua-configuration/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/index.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/spEnrichedFilter.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/spEnrichedFilterContext.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/spEnrichedFilterUnstructEvent.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/spEnrichedSetPk.md
  docs/destinations/forwarding-events/snowbridge/configuration/transformations/snowplow-builtin/spEnrichedToJson.md
  docs/destinations/forwarding-events/snowbridge/getting-started/distribution-and-deployment.md
  docs/destinations/forwarding-events/snowbridge/getting-started/index.md
  docs/destinations/forwarding-events/snowbridge/getting-started/quickstart.md
  docs/destinations/forwarding-events/snowbridge/index.md
  docs/feature-comparison/index.md
  docs/getting-started-on-snowplow-open-source/telemetry/index.md
  docusaurus.config.js
  package.json
  static/_redirects
  yarn.lock
Labels: cla:yes

#270 Clarify first-party requirements
  docs/enriching-your-data/available-enrichments/cookie-extractor-enrichment/index.md
Labels: cla:no

#277 Prepare for e-commerce v0.2.0 release
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-advanced-usage/dbt-duplicates/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-operation/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/index.md
Labels: do not merge

#275 Python 0.13.0
  docs/collecting-data/collecting-from-own-applications/python-tracker/emitters/index.md
  docs/collecting-data/collecting-from-own-applications/python-tracker/intialization/index.md
  docs/collecting-data/collecting-from-own-applications/python-tracker/tracking-specific-events/index.md
  docs/collecting-data/collecting-from-own-applications/python-tracker/upgrading/index.md
  src/componentVersions.js
Labels: cla:yes

#278 RDB Loader 5.3.1
  src/componentVersions.js
Labels: cla:yes

#281 info note to remind customers to send their password through secure form
  docs/modeling-your-data/running-data-models-via-snowplow-bdp/dbt/using-dbt/index.md
Labels: cla:no

#283 Update index.md
  docs/getting-started-with-snowplow-bdp/enterprise/setup-guide-gcp/index.md
Labels: cla:no
