Repository snowplow/documentation, pull requests merged in 2023-06, with the labels that each got.

#472 Fix dangling underscores in Data Structures API docs
  docs/understanding-tracking-design/managing-data-structures-via-the-api-2/index.md
Labels: cla:yes

#474 RDB Loader 5.6.0
  docs/destinations/warehouses-and-lakes/rdb/loading-transformed-data/_automatic-schema-creation.md
  docs/destinations/warehouses-and-lakes/rdb/loading-transformed-data/databricks-loader/index.md
  docs/destinations/warehouses-and-lakes/rdb/loading-transformed-data/redshift-loader/index.md
  docs/destinations/warehouses-and-lakes/rdb/loading-transformed-data/snowflake-loader/index.md
  src/componentVersions.js
Labels: cla:yes

#478 docs: typo
  docs/reusable/untitled-reusable-block-38/_index.md
Labels: cla:yes

#480 Update Igluctl and Igluserver versions
  src/componentVersions.js
Labels: cla:yes

#490 Add web-performance to redirects
  static/_redirects
Labels: cla:yes

#491 Fix url
  static/_redirects
Labels: cla:yes

#482 Fix typo (noun, not verb)
  docs/getting-started-on-snowplow-open-source/quick-start-aws/index.md
Labels: cla:no

#425 Add conversions information - web 0.15.0
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/ecommerce/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/fractribution/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/media-player/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/mobile/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/normalize/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-configuration/web/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/consent-module/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/conversions/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/core-web-vitals-module/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-web-data-model/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-quickstart/web/index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/migration-guides/web/index.md
  package.json
  src/componentVersions.js
  src/components/DbtSchemaSelector/index.js
  src/components/JsonSchemaValidator/index.js
  src/css/custom.css
  yarn.lock
Labels: do not merge

#495 Update docs for Snowplow v3 Tag 2.0.0
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/google-tag-manager-custom-template/template-for-javascript-tracker-v3/tag-template-guide/images/additional_tracking_parameters.png
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/javascript-tracker/google-tag-manager-custom-template/template-for-javascript-tracker-v3/tag-template-guide/index.md
Labels: cla:yes

#496 Update docs for gtm-ss Snowplow tag 0.5.0
  docs/destinations/forwarding-events/google-tag-manager-server-side/snowplow-tag-for-gtm-ss/index.md
Labels: cla:yes

#498 Update docs for gtm-ss Braze tag 0.5.0
  docs/destinations/forwarding-events/google-tag-manager-server-side/braze-tag-for-gtm-ss/braze-tag-configuration/images/snowplow_event_mapping_options.png
  docs/destinations/forwarding-events/google-tag-manager-server-side/braze-tag-for-gtm-ss/braze-tag-configuration/index.md
  docs/destinations/forwarding-events/google-tag-manager-server-side/braze-tag-for-gtm-ss/index.md
Labels: cla:yes

#502 Update to reflect new SSO automation
  docs/using-the-snowplow-console/managing-users/adding-removing/index.md
Labels: cla:yes

#507 Bump dbt version
  src/componentVersions.js
Labels: cla:yes
