Repository snowplow/documentation, pull requests merged in 2024-12, with the labels that each got.

#1064 Updating HTML5 Media Tracking Documentation
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/tracking-events/media/html5/index.md
Labels: cla:yes

#1045 Update index.md
  docs/modeling-your-data/modeling-your-data-with-dbt/index.md
Labels: cla:yes

#1069 change browser context autotracked to false
  docs/collecting-data/collecting-from-own-applications/snowplow-tracker-protocol/ootb-data/device-and-browser/index.md
Labels: cla:no

#1093 Updated typo and made subtitle bold
  docs/modeling-your-data/modeling-your-data-with-dbt/dbt-models/dbt-attribution-data-model/index.md
Labels: cla:yes

#1060 Fixing links and updating page to refer to V4
  docs/collecting-data/collecting-from-own-applications/javascript-trackers/web-tracker/tracker-setup/hosting-the-javascript-tracker/third-party-cdn-hosting/index.md
Labels: cla:yes

#1092 Add snowplow-cli data products
  docs/pipeline-components-and-applications/cli/images/orgID.png
  docs/pipeline-components-and-applications/cli/index.md
  docs/pipeline-components-and-applications/cli/reference/index.md
  docs/recipes/recipe-data-structures-in-git/index.md
  docs/understanding-tracking-design/defining-the-data-to-collect-with-data-poducts/cli/index.md
  docs/understanding-tracking-design/managing-your-data-structures/cli/index.md
Labels: do not merge, cla:yes

#1097 Revert "Add snowplow-cli data products"
  docs/pipeline-components-and-applications/cli/index.md
  docs/pipeline-components-and-applications/cli/reference/index.md
  docs/recipes/recipe-data-structures-in-git/index.md
  docs/understanding-tracking-design/defining-the-data-to-collect-with-data-poducts/cli/index.md
  docs/understanding-tracking-design/managing-your-data-structures/cli/images/orgID.png
  docs/understanding-tracking-design/managing-your-data-structures/cli/index.md
Labels: cla:yes

#1098 Updating to test tagging of pages
  docs/testing-debugging/snowplow-micro/remote-usage/index.md
Labels: cla:yes

#1099 Revert "Updating to test tagging of pages"
  docs/testing-debugging/snowplow-micro/remote-usage/index.md
Labels: cla:yes

#1101 Add data products for snowplow-cli
  docs/data-product-studio/data-products/cli/index.md
  docs/data-product-studio/data-quality/index.md
  docs/data-product-studio/data-structures/manage/cli/index.md
  docs/data-product-studio/data-structures/version-amend/index.md
  docs/data-product-studio/snowplow-cli/images/orgID.png
  docs/data-product-studio/snowplow-cli/index.md
  docs/data-product-studio/snowplow-cli/reference/index.md
  docs/data-product-studio/snowtype/index.md
  docs/resources/recipes-tutorials/recipe-data-structures-in-git/index.md
Labels: cla:yes

#1094 Add file with sample events for Snowbridge local testing
  docs/destinations/forwarding-events/snowbridge/testing/assets/input.txt
  docs/destinations/forwarding-events/snowbridge/testing/index.md
Labels: cla:yes
